# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcpage_setup(wx.Dialog):
#!XRCED:begin-block:xrcpage_setup.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcpage_setup.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "page_setup")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    page_setup_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="page_setup">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Size</label>
                </object>
                <option>0</option>
                <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                <border>5</border>
              </object>
              <object class="spacer">
                <size>10</size>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="paper_size"/>
                <option>4</option>
                <flag>wxTOP|wxBOTTOM|wxEXPAND</flag>
                <border>5</border>
              </object>
              <label>Paper </label>
              <orient>wxHORIZONTAL</orient>
              <object class="spacer">
                <size>5</size>
              </object>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <option>1</option>
        <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxRadioButton" name="portrait">
                  <label>Portrait</label>
                  <value>1</value>
                  <style>wxRB_GROUP</style>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
                <border>5</border>
              </object>
              <object class="sizeritem">
                <object class="wxRadioButton" name="landscape">
                  <label>Landscape</label>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
                <border>5</border>
              </object>
              <label>Orientation</label>
              <orient>wxVERTICAL</orient>
            </object>
            <option>0</option>
            <flag>wxRIGHT|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxFlexGridSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Left</label>
                    </object>
                    <option>1</option>
                    <flag>wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxSpinCtrl" name="left">
                      <size>60,-1</size>
                      <value>5</value>
                      <min>0</min>
                    </object>
                    <option>1</option>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Right</label>
                    </object>
                    <option>1</option>
                    <flag>wxLEFT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                  </object>
                  <object class="sizeritem">
                    <object class="wxSpinCtrl" name="right">
                      <size>60,-1</size>
                      <value>5</value>
                      <min>0</min>
                    </object>
                    <option>1</option>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Top</label>
                    </object>
                    <option>1</option>
                    <flag>wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxSpinCtrl" name="top">
                      <size>60,-1</size>
                      <value>5</value>
                      <min>0</min>
                    </object>
                    <option>1</option>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Bottom</label>
                    </object>
                    <option>1</option>
                    <flag>wxLEFT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                  </object>
                  <object class="sizeritem">
                    <object class="wxSpinCtrl" name="bottom">
                      <size>60,-1</size>
                      <value>5</value>
                      <min>0</min>
                    </object>
                    <option>1</option>
                  </object>
                  <cols>4</cols>
                  <rows>4</rows>
                  <vgap>15</vgap>
                  <hgap>15</hgap>
                </object>
                <flag>wxALL</flag>
                <border>5</border>
              </object>
              <label>Margins (mm)</label>
              <orient>wxVERTICAL</orient>
            </object>
            <option>1</option>
            <flag>wxLEFT|wxEXPAND</flag>
            <border>5</border>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxTOP|wxLEFT|wxRIGHT</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxCheckBox" name="keep_aspect">
                  <label>Keep aspect ratio</label>
                </object>
                <option>1</option>
                <flag>wxALL|wxALIGN_RIGHT</flag>
                <border>5</border>
              </object>
              <object class="sizeritem">
                <object class="wxCheckBox" name="scale_to_page">
                  <label>Scale to page</label>
                </object>
                <option>1</option>
                <flag>wxALL|wxALIGN_LEFT</flag>
                <border>5</border>
              </object>
              <label>Figure shape and scaling</label>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="ID_OK">
              <label>OK</label>
            </object>
          </object>
          <object class="spacer">
            <size>15</size>
            <option>0</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="ID_CANCEL">
              <label>Cancel</label>
            </object>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxBOTTOM|wxLEFT|wxRIGHT|wxALIGN_RIGHT</flag>
        <border>10</border>
      </object>
    </object>
    <title>Page Setup</title>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/page_setup/page_setup_xrc', page_setup_xrc)
    __res.Load('memory:XRC/page_setup/page_setup_xrc')

